version: '3.7'

services:
  yarn:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn
  
  app:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    ports:
      - 3000:3000
    entrypoint: yarn start
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"