export enum PeriodType {
  Year = 'Year',
  Month = 'Month',
  DayOfMonth = 'DayOfMonth',
  DayOfWeek = 'DayOfWeek',
  Hour = 'Hour',
  Minute = 'Minute',
  Second = 'Second',
  StartOfYear = 'StartOfYear',
  StartOfQuarter = 'StartOfQuarter',
  StartOfMonth = 'StartOfMonth',
  Monday = 'Monday',
  StartOfDay = 'StartOfDay',
  StartOfHour = 'StartOfHour',
  StartOfMinute = 'StartOfMinute',
  StartOfFiveMinute = 'StartOfFiveMinute',
  StartOfTenMinutes = 'StartOfTenMinutes',
  StartOfFifteenMinutes = 'StartOfFifteenMinutes',
}
